#page title
page_title                                :  Learn Khasi App                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://learnkhasi.in/donate#ios                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.sngur.learnkhasi&hl=en_US                                          # Enter Google Play Store URL.
donate_link                               : https://learnkhasi.in/donate                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/logo.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Learn Khasi App                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : An app that let users find, ask and answer words with their meaning and sentences in English, Khasi and Garo.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Sngur                                
your_link                                 : https://sngur.com                     
your_city                                 : Shillong                                
email_address                             : sngurshillong@gmail.com
facebook_username                         : sngur.shillong                                         
instagram_username                        : sngur_shillong
twitter_username                          : 
github_username                           : sngur
youtube_username                          : UCa_rUbBbd9IS3Zm0fp6enzg #sngur_shillong #UCa_rUbBbd9IS3Zm0fp6enzg



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Lessons
    description                           : Learn the basics, Listen to Khasi Letters pronunciations, learn simple words.
    fontawesome_icon_name                 : book
    
  - title                                 : Khasi-English-Garo Dictionary
    description                           : Search, Ask and Vote up/down Khasi words and their respective translated English and Garo words.
    fontawesome_icon_name                 : book

  - title                                 : English-Khasi-Garo Dictionary
    description                           : Search, Ask and Vote up/down English words and their respective translated Khasi and Garo words.
    fontawesome_icon_name                 : book

  - title                                 : Sentences
    description                           : Know how to speak/write an English sentence in Khasi and Garo. Add English, Khasi, Garo and Hindi transalations.
    fontawesome_icon_name                 : book

  - title                                 : Earn Points and Level Up
    description                           : Earn points and Unlock more features on each new level.
    fontawesome_icon_name                 : trophy
  
  - title                                 : Levels
    description                           : There are three levels in the app, you first start at level 1.
    fontawesome_icon_name                 : trophy

  - title                                 : Favorites
    description                           : Add Words to your Favorites List
    fontawesome_icon_name                 : star

  - title                                 : Like and Share Words and Sentence transalations
    description                           : Easily share screenshot of words and sentences with your friends, like or vote up correct words and transalations
    fontawesome_icon_name                 : thumbs-up

  - title                                 : Support And Sponsor us
    description                           : Help us make the app and our service better, your support counts.
    fontawesome_icon_name                 : gift



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown